@php $id = app()->getLocale() === 'id'; @endphp
<div class="space-y-8">
    <x-deadline-summary />
    <div class="prose prose-slate max-w-none">
        <h2>{{ $id ? 'Abstrak dan penulis' : 'Abstract and authors' }}</h2>
        <p>{{ $id ? 'Tulis abstrak dalam bahasa Inggris, 150–500 kata, yang merangkum tujuan, metode, hasil, dan kesimpulan. Isi judul, topik, serta 1–5 keywords. Cantumkan semua penulis sesuai urutan dan pilih tepat satu corresponding author. Satu akun dapat mengirim satu paper per edisi.' : 'Write an English abstract of 150–500 words covering the objective, methods, results, and conclusion. Provide a title, topic, and 1–5 keywords. List all authors in order and select exactly one corresponding author. Each account may submit one paper per edition.' }}</p>
        <h2>{{ $id ? 'Review sampai LOA' : 'Review and acceptance' }}</h2>
        <p>{{ $id ? 'Simpan draft dan periksa preview PDF sebelum mengirim. Abstrak dikunci selama review. Jika diminta revisi, baca komentar reviewer, perbaiki, lalu kirim ulang. Setelah panitia menerima abstrak, LOA terbit otomatis dan dapat diunduh dari detail paper.' : 'Save your draft and check the PDF preview before submitting. The abstract is locked during review. If revisions are requested, read the feedback, edit, and resubmit. Once the committee accepts the abstract, the LOA is issued automatically and can be downloaded from the paper details.' }}</p>
        <h2>{{ $id ? 'Invoice dan pembayaran' : 'Invoice and payment' }}</h2>
        <p>{{ $id ? 'Setelah LOA terbit, invoice dibuat sesuai kategori Anda. Jika ditawarkan reviewer, opsi publikasi SINTA 3 dapat dipilih sebelum transaksi dimulai. Total dan rincian biaya ditampilkan sebelum pembayaran. Untuk harga USD, kurs serta total penagihan IDR ditampilkan pada invoice dan tidak berubah sesudah diterbitkan. Jika status belum diperbarui, gunakan Periksa Status Pembayaran; jangan membuat pembayaran kedua.' : 'After the LOA is issued, an invoice is created for your category. If offered by the reviewers, the SINTA 3 option can be selected before starting payment. Review the total and breakdown before paying. USD prices show a fixed exchange rate and IDR billing total on the invoice. If payment confirmation is delayed, use Check Payment Status rather than paying twice.' }}</p>
        <h2>{{ $id ? 'Menyiapkan full paper' : 'Preparing the full paper' }}</h2>
        <p>{{ $id ? 'Unggah full paper setelah pembayaran terverifikasi. Format yang diterima: PDF, DOC, atau DOCX, maksimum 20 MB. Gunakan template naskah di bawah sebagai struktur awal: judul, penulis dan afiliasi, abstrak, pendahuluan, metode, hasil dan pembahasan, kesimpulan, serta referensi. Ketentuan tambahan jurnal tujuan mengikuti pengumuman panitia atau editor jurnal.' : 'Upload the full paper after payment is verified. Accepted formats are PDF, DOC, and DOCX, up to 20 MB. Use the manuscript template below as a starting structure: title, authors and affiliations, abstract, introduction, methods, results and discussion, conclusion, and references. Additional requirements for a target journal follow committee or journal editor announcements.' }}</p>
        <p>{{ $id ? 'Deadline full paper ditampilkan di atas. Jika masih “akan diumumkan”, tanggal final belum ditetapkan. Versi unggahan sebelumnya disimpan secara privat ketika Anda mengirim pengganti.' : 'The full paper deadline is displayed above. If it says “To be announced”, the final date has not been set. Previous uploaded versions are retained privately when you submit a replacement.' }}</p>
        <h2>{{ $id ? 'Presentasi dan sertifikat' : 'Presentation and certificates' }}</h2>
        <p>{{ $id ? 'Ikuti jadwal dalam WITA (UTC+8). Akses Zoom dan penempatan sesi disampaikan panitia kepada peserta terdaftar. Sertifikat presenter mensyaratkan pembayaran, presentasi, dan pengiriman full paper; sertifikat peserta seminar mensyaratkan kehadiran pada sesi utama.' : 'Follow the schedule in Central Indonesia Time (UTC+8). The committee provides Zoom access and session assignments to registered participants. Presenter certificates require payment, presentation, and full paper submission; seminar attendee certificates require attendance at the main sessions.' }}</p>
    </div>
    <div class="flex flex-wrap gap-3">
        <a href="{{ route('manuscript-template') }}" class="btn btn-primary">{{ $id ? 'Unduh template naskah DOCX' : 'Download manuscript template DOCX' }}</a>
        <a href="{{ route('contact') }}" class="btn btn-outline">{{ $id ? 'Bantuan panitia' : 'Contact the committee' }}</a>
    </div>
</div>
